export const SET_LOADING_USER = "SET_LOADING_USER";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_ERROR = "LOAD_USER_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const LOG_OUT = "LOG_OUT";
export const SEND_PHONE_SUCCESS = "SEND_PHONE_SUCCESS";
export const SEND_PHONE_ERROR = "SEND_PHONE_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const GET_PIN_SUCCESS = "GET_PIN_SUCCESS";
export const GET_PIN_ERROR = "GET_PIN_ERROR";
export const CHECK_PIN_SUCCESS = "CHECK_PIN_SUCCESS";
export const CHECK_PIN_ERROR = "CHECK_PIN_ERROR";

export const SET_LOADING_CONTRACTS = "SET_LOADING_CONTRACTS";
export const LOAD_CONTRACTS_SUCCESS = "LOAD_CONTRACTS_SUCCESS";
export const LOAD_CONTRACTS_ERROR = "LOAD_CONTRACTS_ERROR";
