export const SET_LOADING_USER = "SET_LOADING_USER";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_ERROR = "LOAD_USER_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const SET_LOADING_CONTRACTS = "SET_LOADING_CONTRACTS";
export const LOAD_CONTRACTS_SUCCESS = "LOAD_CONTRACTS_SUCCESS";
export const LOAD_CONTRACTS_ERROR = "LOAD_CONTRACTS_ERROR";
